export const MESSAGES_RESPONSE = {
  Forbidden: `You don't have permissions`,
  NoRecord: `No record found`,
};
export const ROLES = {
  admin: 'admin',
  user: 'user',
  moderator: 'moderator',
};

export const IOS_NOTIFICATION_TYPES = {
  RENEWAL: 'RENEWAL',
  INTERACTIVE_RENEWAL: 'INTERACTIVE_RENEWAL',
  CANCEL: 'CANCEL',
  INITIAL_BUY: 'INITIAL_BUY',
  DID_CHANGE_RENEWAL_STATUS: 'DID_CHANGE_RENEWAL_STATUS',
  DID_CHANGE_RENEWAL_PREF: 'DID_CHANGE_RENEWAL_PREF',
};

export const ANDROID_NOTIFICATION_TYPES = {
  SUBSCRIPTION_RECOVERED: 1,
  SUBSCRIPTION_RENEWED: 2,
  SUBSCRIPTION_CANCELED: 3,
  SUBSCRIPTION_PURCHASED: 4,
  SUBSCRIPTION_ON_HOLD: 5,
  SUBSCRIPTION_IN_GRACE_PERIOD: 6,
  SUBSCRIPTION_RESTARTED: 7,
  SUBSCRIPTION_PRICE_CHANGE_CONFIRMED: 8,
  SUBSCRIPTION_DEFERRED: 9,
  SUBSCRIPTION_PAUSED: 10,
  SUBSCRIPTION_PAUSE_SCHEDULE_CHANGED: 11,
  SUBSCRIPTION_REVOKED: 12,
  SUBSCRIPTION_EXPIRED: 13,
};
